update github actions

diff --git a/.github/workflows/rush-build.yaml b/.github/workflows/rush-build.yaml
--- a/.github/workflows/rush-build.yaml
+++ b/.github/workflows/rush-build.yaml
@@ -3,14 +3,14 @@ on:
   workflow_dispatch:
     inputs:
       rebuild:
-        description: 'Rebuild without cache (default false)'
+        description: 'rush rebuild insteadof build (default yes)'
         required: false
-        default: false
+        default: true
   push:
     branches:
       - master
 env:
-  NODE_ENV: production
+  NODE_ENV: development
   NEVER_UNSHARE: yes
 jobs:
   cancel:
@@ -18,7 +18,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: cancel running workflows
-        uses: GongT/cancel-previous-workflows@v1.1
+        uses: GongT/cancel-previous-workflows@6dd7af8389c9434cc893fd33b58609e73db49fbe
         env:
           GITHUB_TOKEN: ${{ github.token }}
           DELETE: 'yes'
@@ -26,22 +26,40 @@ jobs:
     runs-on: ubuntu-latest
     name: 'Run build with rush'
     steps:
-      - name: 'Checkout'
+      - name: '签出代码'
         uses: actions/checkout@v2
         with:
           submodules: 'recursive'
           clean: false
           fetch-depth: 0
-      - name: Cache multiple paths
+
+      - name: 'npm下载缓存'
         uses: actions/cache@v2
         with:
           path: ~/.pnpm-store
           key: pnpm
-      - name: 'Install'
+
+      - name: '安装npm依赖'
         run: node common/scripts/install-run-rush.js update
-      - name: 'Build'
+
+      - name: '运行构建（带缓存）'
         if: '!${{ github.event.inputs.rebuild }}'
         run: node common/scripts/install-run-rush.js build
-      - name: 'Rebuild'
+
+      - name: '运行全部构建过程'
         if: '${{ github.event.inputs.rebuild }}'
         run: node common/scripts/install-run-rush.js rebuild
+
+      - name: '检查构建状态'
+        run: |
+          git add .
+          if [[ "$(git status --porcelain)" ]]; then
+            git status
+            echo "::error ::构建后有文件发生变化" >&2
+            exit 1
+          fi
+
+      - name: '发布版本号有变化的包到NPM'
+        run: node common/scripts/install-run-rush.js ypublish
+        env:
+          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
